extends Node

# https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-load-threaded-request
const SCENE_PATH := "res://features/combat/presentation/widgets/health_bar/variants/large/health_bar_with_a_very_long_name.tscn"


func irreducible_line():
	var store: AnAutoGeneratedInventoryStoreServiceClient = AnAutoGeneratedInventoryStoreServiceClientFactory.create()
	var total := store.first_value + store.second_value + store.third_value + store.fourth_value + store.v
	print(store, total, SCENE_PATH)
